### ISSUE TITLE
no compiler.properties. in line 52. i would be crash...where the property file?

### ISSUE THREAD

**Issue by afeihehe** [imsizon/ant-android-scala#2]
my android sdk tools is 21.1,
platform-tools is 16.0.1
my scala is 2.9.1 final

-compile:
    [javac] Compiling 1 source file to /Users/zhangpengfei/Documents/workspaceAAfei/testMemory/bin/classes

scala-compile:
 [property] Unable to find resource compiler.properties
   [scalac] Scala version ${scala.version.number} - http://scala-lang.org
BUILD FAILED
/Users/zhangpengfei/Documents/codes/ant-android-scala/build-scala.xml:52: Problem: failed to create task or type scalac
Cause: The name is undefined.
Action: Check the spelling.
Action: Check that any custom tasks/types have been declared.
Action: Check that any <presetdef>/<macrodef> declarations have taken place.

**Comment by imsizon** [comment]
Please check your environment config in local.properties to ensure that `scala.dir` is right

**Comment by afeihehe** [comment]
i`m very grateful to received your anwser. 
i think the path is right, and i install scala use : brew install scala
and i cant find the file in the folder /usr/local/Cellar/scala/2.9.1

is the version problem?
this is my local.properties:

sdk.dir=/Users/zhangpengfei/work/android-sdk-macosx
scala.dir=/usr/local/Cellar/scala/2.9.1
proguard.dir=/Users/zhangpengfei/work/android-sdk-macosx/tools/proguard

ant.android.scala.dir=/Users/zhangpengfei/Documents/codes/ant-android-scala

scala.library.installed=false

key.store=
key.alias=

key.store.password=
key.alias.password=

**Comment by afeihehe** [comment]
thsi is my scala folder:

ZPF-MBP:2.9.1 zhangpengfei$ pwd
/usr/local/Cellar/scala/2.9.1
ZPF-MBP:2.9.1 zhangpengfei$ ls
INSTALL_RECEIPT.json    bin         etc         libexec         share

**Comment by afeihehe** [comment]
i waited flower die and hope you can give me direction 。。。i`m so tragedy

**Comment by afeihehe** [comment]
now i found the path error, 
my library is 
<property name="scala-compiler.jar" value="${scala.dir}/libexec/lib/scala-compiler.jar" />
and your code is 
<property name="scala-compiler.jar" value="${scala.dir}/lib/scala-compiler.jar" />

and then the other problem, cant find some var and reference:

extensible.classpath
extensible.libs.classpath
project.libraries.jars

cant you tell me what`s the var meaning and i think i can modify the build-scala.xml myself, thanks a lot

**Comment by afeihehe** [comment]
you are so let me down...bye
